name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy
        run: |
          mv "Fair Pricing and Quality Optimization in Amsterdam Airbnb Market"/* .
          git add .
          git commit -m "Deploy website from subfolder"
          git push
