project:
  type: website
  output-dir: Fair Pricing and Quality Optimization in Amsterdam Airbnb Market
  preview:
    port: 3333

website:
  title: "Fair Pricing and Quality Optimization in Amsterdam's Airbnb Market"
  page-footer:
    left: "shihang-yan@outlook.com"

  sidebar:
    logo: "images/air.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ShihangHeisenberg
        text: "Shihang"
    style: "docked"
    search: true
    collapse-level: 8
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-static-images.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true
